server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ums_portal?userUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: ${UMS_PORTAL_ADMIN}
    password: ${UMS_PORTAL_ADMIN_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL57Dialect
  h2:
    console:
      enabled: false
